# Generated by Django 4.1.4 on 2023-01-05 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("ba99740a-d494-48b4-a851-c57e9f9b3df5"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="productintensity",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("f20e568b-7528-4536-91a6-729243d36a58"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("22c5ae7e-a9af-4d52-86fd-a83c668d3007"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
