# Generated by Django 4.1.4 on 2023-01-05 14:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_product_id_alter_productintensity_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("7c2c43c3-9d57-4294-972b-5b20699ed5ba"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="productintensity",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("67b17729-7df7-4f20-a1a2-18f9291302be"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="productstock",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_product",
                to="product.product",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("230b7982-f3b9-4646-846c-8b9d4fd83f6c"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
