# Generated by Django 4.1.4 on 2023-01-05 14:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_id_alter_productintensity_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productintensity",
            old_name="product_intensity",
            new_name="intensity",
        ),
        migrations.RenameField(
            model_name="producttype",
            old_name="product_type",
            new_name="type",
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("414e514d-aa98-4f0e-a96d-fc150a4b1e52"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_intensity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_intensity",
                to="product.productintensity",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_type",
                to="product.producttype",
            ),
        ),
        migrations.AlterField(
            model_name="productintensity",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("cd720f9f-b2cf-4478-bff2-93d7752c3469"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("829d9b4d-bd13-467e-b26d-e452529d63e0"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
