# Generated by Django 4.1.4 on 2023-01-06 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_product_id_alter_productintensity_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("6f52e1df-a1f0-4489-a732-1101022cce7d"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="productintensity",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("f090329c-58b1-45b8-bdae-f677940dae7f"),
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("3dca1f4f-42c5-40e0-be99-2e4d9e76058f"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
