# Generated by Django 4.1.4 on 2023-01-08 16:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_product_id_alter_productintensity_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("fc614ce1-544e-43df-9b8d-48b9d5d7248d"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="productintensity",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d86df9f4-95ee-43c4-9b59-5102aeed61e5"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b01b86ad-fa92-4380-8572-1f2ae31fa133"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
