# Generated by Django 4.1.4 on 2023-01-09 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_alter_productimage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("fb4a64ab-4659-482b-bd17-07255842ce98"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="productintensity",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("275e1ac4-c0c1-452d-b988-da87f6cb0726"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("acd32c50-e256-4f49-b517-b8cad72e2bf6"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
