# Generated by Django 4.1.4 on 2023-01-09 19:01

import common.validators.file_size
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import functools
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_alter_product_id_alter_product_product_intensity_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JoinedProduct",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="product.product",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        upload_to="product/",
                        validators=[
                            functools.partial(
                                common.validators.file_size.validate_file_size,
                                *(),
                                **{"file_size": 10}
                            ),
                            django.core.validators.FileExtensionValidator(
                                [
                                    "jpg",
                                    "jpeg",
                                    "pdf",
                                    "txt",
                                    "png",
                                    "svg",
                                    "mpeg",
                                    "gif",
                                    "webm",
                                    "MOV",
                                    "mkv",
                                    "HEIC",
                                    "JPG",
                                    "PNG",
                                    "JPEG",
                                    "GIF",
                                    "SVG",
                                ],
                                "allowed format is :  'jpg', 'png', 'jpeg',  'gif','svg'... ",
                            ),
                        ],
                        verbose_name="Product Image",
                    ),
                ),
            ],
            options={
                "managed": False,
            },
            bases=("product.product",),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("55375403-a943-4f59-94b7-d5d20ac6e2c6"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="productintensity",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("b92dce14-d8c8-4ee8-a4b4-db004f658595"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("eadd50da-2735-44b1-b88d-2dd525b91287"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
