# Generated by Django 4.1.4 on 2023-01-10 14:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_joinedproduct_alter_product_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("3a6f7953-cd21-472c-b715-5540a26975ea"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="productintensity",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("e1a3329b-0c3e-419f-b024-5fcdff8f8a22"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("41718221-2ca7-4b95-b3d0-b6f73459dc56"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.DeleteModel(
            name="JoinedProduct",
        ),
    ]
