# Generated by Django 4.1.4 on 2022-12-29 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_useraddress_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_address",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
