# Generated by Django 4.1.4 on 2022-12-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_useraddress_created_at_useraddress_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraddress",
            name="is_default",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
